jobs:
- job: iOS

  pool:
    vmImage: macOS-11

  variables:
    - name: NUGET_PACKAGES
      value: $(build.sourcesdirectory)/.nuget
    - name: VersionCodeOffset
      value: 400559 # last value for the APK release
    - group: apple.appstore.distribution

  workspace:
     clean: all

  steps:

  - template: build/uno-ci/canary-updater.yml
  - template: build/uno-ci/gitversion.yml
  - template: build/uno-ci/dotnet-install-mac.yml
  - template: build/uno-ci/jdk-setup.yml

  - task: UseDotNet@2
    displayName: 'Use .Net Core runtime 3.1.201'
    retryCountOnTaskFailure: 3
    inputs:
      packageType: runtime
      version: 3.1.3

  - task: InstallAppleCertificate@2
    displayName: Install Certificate
    inputs:
      certSecureFile: apple.appstore.distribution.p12
      certPwd: $(appleappstorecertificatepassword)
      keychain: temp
      deleteCert: true

  - task: InstallAppleProvisioningProfile@1
    displayName: Install Provisioning Profile
    inputs:
      provisioningProfileLocation: secureFiles
      provProfileSecureFile: Uno_Calculator.mobileprovision

  - bash: |
      cd $(build.sourcesdirectory)/src/CalcManager
      chmod +x build_ios.sh
      ./build_ios.sh

    displayName: Build native CalcManager

  - task: MSBuild@1
    inputs:
      solution: '$(build.sourcesdirectory)/src/build/build.csproj'
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r  /p:BuildPlatformTarget=iOS /bl:$(build.artifactstagingdirectory)/build.binlog 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: true
      createLogFile: true

  - bash: |
      cd $(build.sourcesdirectory)/src/Calculator.mobile
      dotnet build -f net6.0-ios -c Release -r ios-arm64 /p:ArchiveOnBuild=true /bl:$(build.artifactstagingdirectory)/build.binlog "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION"

    displayName: 'Build iOS Binaries (net6)'

  - task: CopyFiles@2
    displayName: 'Publish iOS Binaries (net6)'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.Mobile/bin/Release/net6.0-ios/ios-arm64
      Contents: '*.ipa'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: MSBuild@1
    inputs:
      solution: '$(build.sourcesdirectory)/src/Calculator.iOS/Calculator.iOS.csproj'
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /p:Platform=iPhone /bl:$(build.artifactstagingdirectory)/build.binlog  "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: true
      createLogFile: true

  - task: CopyFiles@2
    displayName: 'Publish iOS Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.iOS/bin/iPhone/Release
      Contents: '*.ipa'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    retryCountOnTaskFailure: 3
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: Uno-Calculator-iOS
      ArtifactType: Container
